### Crear una barbería
POST http://localhost:8000/barberias/
Content-Type: application/json

{
  "nombre": "Barbería juanito",
  "direccion": "Calle 123 #45-67",
  "telefono": "3001506",
  "email": "contacto@gmail.com.com"
}

### Obtener todas las barberías
GET http://localhost:8000/barberias/

### Obtener barbería por ID
GET http://localhost:8000/barberias/2

### Actualizar una barbería
PUT http://localhost:8000/barberias/2
Content-Type: application/json

{
  "nombre": "Barbería nueva",
  "direccion": "Nueva dirección 999",
  "telefono": "3007654321",
  "email": "nuevo@barberiarenovada.com"
}

### Eliminar barbería por ID
DELETE http://localhost:8000/barberias/1
